version: '3'

services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4